name: uni_links2
version: 0.6.0+2
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.1 <3.0.0'

dependencies: 
  dependencies: 
  uni_links2_platform_interface: 
    path: ../uni_links_platform_interface
  uni_links_web2: 
    path: ../uni_links_web
  flutter: 
    sdk: flutter

dev_dependencies: 
  pedantic: ^1.11.1
  flutter_test: 
    sdk: flutter

flutter: 
  plugin: 
    platforms: 
      android: 
        package: name.avioli.unilinks
        pluginClass: UniLinksPlugin
      ios: 
        pluginClass: UniLinksPlugin
